@temp_HostAddress = http://localhost:5062
@token = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJXZWJBcGkiLCJpc3MiOiJBcGlBdXRoZW50aWNhdGlvbiIsImV4cCI6MTc4MzEwNzg3MSwic3ViIjoiMDE5ZjI5N2UtNGZkZC03MGE3LTg1NTgtYzg2OTNmODhkYmQxIiwiU2VncmVnYXRpb24tS2V5IjoiOTE1NjI3OTgtMjM1Mi00NWE3LTgyNTctOWUwZjAwOTEyODNiIiwiaWF0IjoxNzgzMTA3NTcxLCJuYmYiOjE3ODMxMDc1NzF9.aOqeKl0XDRNxPFbExzaP1rZloRZp0KdlhHwZXqmfohJnPifkqtIcneayQgLKBtmLH_SpThfAdDImtcMjKJEH3g

GET {{temp_HostAddress}}/login/
Accept: application/json

###

GET {{temp_HostAddress}}/weatherforecast/
Authorization: Bearer {{token}}
Accept: application/json

###

GET {{temp_HostAddress}}/revoke
Authorization: Bearer {{token}}
Accept: application/json