@temp_HostAddress = http://localhost:5062
@token = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJXZWJBcGkiLCJpc3MiOiJBcGlBdXRoZW50aWNhdGlvbiIsImV4cCI6MTc4MzE1MjU1OCwic3ViIjoiMDE5ZjJjMjgtMmYwNi03Njc3LWJlNjYtZTQ2ODQ1NmQ1OGJkIiwic2VncmVnYXRpb24ta2V5IjoiMjU3NDI5MTYtMzZjOC00MGJlLTlmYjAtZGI0ODE4NGE5NzI3IiwiaWF0IjoxNzgzMTUyMjU4LCJuYmYiOjE3ODMxNTIyNTh9.2vovw9io3UOWvxJNbRR1-yRJTw1q_wNOKoJuFA3tMa7dljCslezumns9SnT-HkxbmLIHRfAI_x7naW2POUOnAg

GET {{temp_HostAddress}}/login/
Accept: application/json

###

GET {{temp_HostAddress}}/weatherforecast/
Authorization: Bearer {{token}}
Accept: application/json

###

GET {{temp_HostAddress}}/revoke
Authorization: Bearer {{token}}
Accept: application/json