@temp_HostAddress = http://localhost:5062
@token = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJXZWJBcGkiLCJpc3MiOiJBcGlBdXRoZW50aWNhdGlvbiIsImV4cCI6MTc3MzU2MTY4NCwic3ViIjoiMDE5Y2YwN2YtMGRiNS03ZDNhLTliZGUtODAyNTE3MWE2MGY0IiwiaWF0IjoxNzczNTYxMzg0LCJuYmYiOjE3NzM1NjEzODR9.CS1OdLoT_QykCTdHGKmc-F8HkL1CqhHqMwqqHNConCUWQAulVBTyT9w90x_LVFDcGtUPB7TmJ_Vf7pWK2BkbAw

GET {{temp_HostAddress}}/login/
Accept: application/json

###

GET {{temp_HostAddress}}/weatherforecast/
Authorization: Bearer {{token}}
Accept: application/json

###

GET {{temp_HostAddress}}/revoke
Authorization: Bearer {{token}}
Accept: application/json